#!/bin/bash
# I get a lot of errors printed to the console like this:
# [warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
# this export line is an attempt to stop that
export EVENT_NOKQUEUE=1
npm install && npm start

